In [35]:
import pandas as pd
import numpy as np
df = pd.DataFrame(pd.read_csv(r'C:\Users\user\OneDrive\Desktop\git_folder\202008-youth-bigdata\bokyoung\naver_news.csv'))
df

,Unnamed: 0,date,title,content
0,0,2020.09.10,"임영진 신한카드 대표, 코로나19 관심도 '업계 1위'",// flash 오류를 우회하기 위한 함수 추가\nfunction _flash_re...
1,1,2020.09.10,항공권 취소 카드사-고객 법적대응...이스타 '진퇴양난',// flash 오류를 우회하기 위한 함수 추가\nfunction _flash_re...
2,2,2020.09.11,"코로나 재확산에 8월 내수 '직격탄'…""경기회복 주춤""",// flash 오류를 우회하기 위한 함수 추가\nfunction _flash_re...
3,3,2020.09.09,"코로나 재확산에 KDI마저…""韓경제 '-1.1%' 역성장""",// flash 오류를 우회하기 위한 함수 추가\nfunction _flash_re...
4,4,2020.09.10,"임영진 신한카드 대표, 코로나19 관심도 '업계 1위'",// flash 오류를 우회하기 위한 함수 추가\nfunction _flash_re...
...,...,...,...,...
1845,1845,2020.09.10,"임영진 신한카드 대표, 코로나19 관심도 '업계 1위'",// flash 오류를 우회하기 위한 함수 추가\nfunction _flash_re...
1846,1846,2020.09.10,항공권 취소 카드사-고객 법적대응...이스타 '진퇴양난',// flash 오류를 우회하기 위한 함수 추가\nfunction _flash_re...
1847,1847,2020.09.11,"코로나 재확산에 8월 내수 '직격탄'…""경기회복 주춤""",// flash 오류를 우회하기 위한 함수 추가\nfunction _flash_re...
1848,1848,2020.09.09,"코로나 재확산에 KDI마저…""韓경제 '-1.1%' 역성장""",// flash 오류를 우회하기 위한 함수 추가\nfunction _flash_re...
1849,1849,2020.09.10,코로나19 재확산에…하반기 채용도 미루는 카드업계,// flash 오류를 우회하기 위한 함수 추가\nfunction _flash_re...

In [36]:
import re 
# '한글'을 제외한 다른 문자 모두 제거
remove_except_ko = re.compile(r"[^가-힣ㄱ-ㅎㅏ-ㅣ\\s]")
def preprocess(text):
    text = re.sub(remove_except_ko,' ',text).strip()
    return text

df['contents'] = df['content'].map(lambda x : preprocess(x))

In [37]:
df.head()

,Unnamed: 0,date,title,content,contents
0,0,2020.09.10,"임영진 신한카드 대표, 코로나19 관심도 '업계 1위'",// flash 오류를 우회하기 위한 함수 추가\nfunction _flash_re...,s 오류를 우회하기 위한 함수 추가 s ...
1,1,2020.09.10,항공권 취소 카드사-고객 법적대응...이스타 '진퇴양난',// flash 오류를 우회하기 위한 함수 추가\nfunction _flash_re...,s 오류를 우회하기 위한 함수 추가 s ...
2,2,2020.09.11,"코로나 재확산에 8월 내수 '직격탄'…""경기회복 주춤""",// flash 오류를 우회하기 위한 함수 추가\nfunction _flash_re...,s 오류를 우회하기 위한 함수 추가 s ...
3,3,2020.09.09,"코로나 재확산에 KDI마저…""韓경제 '-1.1%' 역성장""",// flash 오류를 우회하기 위한 함수 추가\nfunction _flash_re...,s 오류를 우회하기 위한 함수 추가 s ...
4,4,2020.09.10,"임영진 신한카드 대표, 코로나19 관심도 '업계 1위'",// flash 오류를 우회하기 위한 함수 추가\nfunction _flash_re...,s 오류를 우회하기 위한 함수 추가 s ...

In [38]:
from konlpy.tag import Mecab
mecab = Mecab()
# mecab 사용해 토큰화, 한글자 제거, stop_word 제거
stop_word = ['께서','에서','이다','에게','으로','이랑','까지','부터','하다','s',
             '데일리','뉴스','기자','오류','우회','위한','함수','추가',
            '습니다','확산','지난','거리','전망','코로나','카드']
stopPos = ['JKS','JKC','JKG','JKO','JKB','JKV','JKQ','JC','JX',
           'SF','SE','SS','SP','SSO','SSC','SC','SY','SH','SL','SN',
           'MM','MAG','MAJ']
def token_mecab(text):
    text = mecab.pos(text)
    text = [i for i in text if len(i[0])>1]
    text = [i for i in text if i[0] not in stop_word]
    text = [i[0] for i in text if i[1] not in stopPos]
    return text

In [39]:
# 토큰화 + 토큰리스트 생성 
def make_tokens(df):
    df['tokens'] = ''
    tokens_list=[]
    for i, row in df.iterrows():
        if i%500==0:
            print(i,'/',len(df))
        token = token_mecab(df['contents'][i])
        df['tokens'][i] = ' '.join(token)
    return df

df = make_tokens(df)

0 / 1850

C:\Users\user\anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

500 / 1850
1000 / 1850
1500 / 1850

In [40]:
docs= list(df['tokens'])

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidv = TfidfVectorizer()
tfidv = tfidv.fit(docs)
tfidv.transform(docs).toarray()
vocab= tfidv.get_feature_names()

In [42]:
tfidv.transform(docs).toarray()[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07056923, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07056923, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07056923, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.02840013, 0.03533256,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.098115  , 0.07056923, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.15379928, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06003343,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.21170768, 0.        , 0.03469075, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07056923, 0.        , 0.07056923, 0.        , 0.        ,
       0.        , 0.05126643, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.03533256, 0.        ,
       0.        , 0.        , 0.        , 0.07056923, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.03847378, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.06003343, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.15042032, 0.        , 0.        , 0.        ,
       0.        , 0.60168127, 0.0852004 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.13373477, 0.        , 0.        , 0.07056923, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.12006687, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.04457826, 0.        , 0.        , 0.        , 0.        ,
       0.07056923, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07056923, 0.        , 0.        ,
       0.        , 0.        , 0.07056923, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.14113845, 0.        ,
       0.        , 0.        , 0.05014011, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05126643, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07056923, 0.        ,
       0.09099521, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07056923, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07056923, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.06003343, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05126643,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.28227691, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.03996627,
       0.05126643, 0.        , 0.        , 0.        , 0.07066512,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07056923, 0.14113845, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07056923, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.21170768,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07056923, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.03598949, 0.        , 0.        ,
       0.07056923, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07056923, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07056923, 0.07056923, 0.        , 0.        ,
       0.        , 0.14113845, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07056923, 0.        ,
       0.02840013, 0.        , 0.        , 0.07056923, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.21170768, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07056923, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07056923, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07056923, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05014011, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05126643, 0.14113845, 0.        , 0.        , 0.        ,
       0.07056923, 0.        , 0.07056923, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.14113845,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.07056923,
       0.        , 0.        , 0.        , 0.        , 0.03598949,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.10253286, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.07056923,
       0.        , 0.        , 0.05126643, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05126643, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.03533256, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05014011,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.04457826, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05126643,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [43]:
import pandas as pd
df = pd.DataFrame(tfidv.transform(docs).toarray(), columns = vocab)
df

,가구,가능,가맹점,가세,가스,가운데,가정,가족,각종,간다든가,...,회복세,회의,회장,효과,효율,후보,휴폐,흐름,희망,힘입
0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000
1,0.0,0.000000,0.041047,0.000000,0.0,0.000000,0.0,0.041047,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000
2,0.0,0.064975,0.000000,0.000000,0.0,0.023601,0.0,0.000000,0.032487,0.000000,...,0.129950,0.062943,0.0,0.046165,0.000000,0.000000,0.0,0.070803,0.0,0.000000
3,0.0,0.000000,0.000000,0.027705,0.0,0.020127,0.0,0.000000,0.000000,0.027705,...,0.000000,0.000000,0.0,0.039370,0.055411,0.027705,0.0,0.020127,0.0,0.027705
4,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1845,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000
1846,0.0,0.000000,0.041047,0.000000,0.0,0.000000,0.0,0.041047,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000
1847,0.0,0.064940,0.000000,0.000000,0.0,0.023588,0.0,0.000000,0.032470,0.000000,...,0.129879,0.062909,0.0,0.046140,0.000000,0.000000,0.0,0.070765,0.0,0.000000
1848,0.0,0.000000,0.000000,0.027705,0.0,0.020127,0.0,0.000000,0.000000,0.027705,...,0.000000,0.000000,0.0,0.039370,0.055411,0.027705,0.0,0.020127,0.0,0.027705
1849,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000

In [44]:
# sum tfidf frequency of each term through documents
sums = df.sum(axis=0)
sums

가구      2.643289
가능     25.945730
가맹점    17.907894
가세     11.082155
가스      2.643289
         ...
후보     11.082155
휴폐      1.321645
흐름     36.361502
희망      1.321645
힘입     11.082155
Length: 805, dtype: float64

In [45]:
sums.sort_values(ascending=False)

대표       259.272491
이스타항공    211.916794
경제       207.083630
경기       188.157071
대금       161.171049
            ...
늘어나        1.321645
의결         1.321645
달라         1.321645
당부         1.321645
임대료        1.321645
Length: 805, dtype: float64

In [46]:
df_sum = pd.DataFrame(sums.sort_values(ascending=False))
df_sum

                0
대표     259.272491
이스타항공  211.916794
경제     207.083630
경기     188.157071
대금     161.171049
...           ...
늘어나      1.321645
의결       1.321645
달라       1.321645
당부       1.321645
임대료      1.321645

[805 rows x 1 columns]

In [48]:
# 단어 빈도수 순
df_sum.head(25)

                0
대표     259.272491
이스타항공  211.916794
경제     207.083630
경기     188.157071
대금     161.171049
성장     155.150172
채용     152.065449
환불     143.263155
수장     112.910762
승객     105.958397
사회     104.185915
내수     103.920411
시작     103.920411
증가     102.419683
올해      91.625896
승인      90.930360
영향      90.895987
국내      89.830362
취소      89.539472
돌려받     89.539472
한국      88.657241
임영진     84.683072
글로벌     84.683072
연구소     84.683072
두기      82.375759